language: cpp
compiler: gcc
sudo: required
dist: trusty
    
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
#  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update

install:
  - sudo apt-get install g++-7 gcc-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  - sudo apt-get install dh-make
  - "sudo apt-get install freetds-common libbluetooth3 libegl1-mesa-drivers libmng2 libmtdev1
  libopenal-data libopenal1 libopenvg1-mesa libopus0 libsdl2-2.0-0 libsnappy1
  libsybdb5 libwayland-egl1-mesa libwebp5 libwebpdemux1 libxcb-icccm4
  libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 qt59base
  qt59connectivity qt59gamepad qt59graphicaleffects qt59imageformats 
  qt59location qt59multimedia qt59quickcontrols qt59quickcontrols2 
  qt59remoteobjects qt59script qt59scxml qt59sensors qt59serialbus 
  qt59serialport qt59speech qt59svg qt59tools qt59translations 
  qt59webchannel qt59websockets qt59x11extras qt59xmlpatterns qt59charts-no-lgpl"
  
script:
  - source /opt/qt59/bin/qt59-env.sh
#  - source /opt/qt510/bin/qt510-env.sh
  - /opt/qt59/bin/qmake Loja.pro
  - make -j3
  
  # TODO:
  # cache ccache cache folder?
  # cache /usr/bin
  # cache qt folder /opt/qt?