language: cpp
cache: ccache
sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env: COMPILER=g++-7
#      env: CXX=g++-7
#      env: CC=gcc-7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
      env: COMPILER=clang++-3.9
    
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
  - sudo apt-get update

install:
  - sudo apt-get install -y qt59-meta-full dh-make
  
script:
  # Link gcc-6 and g++-6 to their standard commands
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  #- export CC=/usr/bin/gcc-7
  #- export CXX=/usr/bin/g++-7
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v
  # Run your build commands next
  #- source /opt/qt59/bin/qt59-env.sh
  #- /opt/qt59/bin/qmake Loja.pro
  #- ccache make -j4
