language: cpp

dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=g++-7
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - clang-3.9
#      env: COMPILER=clang++-3.9
    
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y;
  - sudo apt-get update

install:
  - sudo apt-get install -y qt59-meta-full dh-make
#  - sudo apt-get install -y gcc-7 g++-7
#  - sudo apt-get install -y qt59-meta-full
#  qt59base qt59script dh-make gcc-7 g++-7;
  
script:
  - source /opt/qt59/bin/qt59-env.sh;
  - /opt/qt59/bin/qmake Loja.pro
  - make -j4
