language: cpp
compiler: gcc
dist: bionic
cache: ccache

addons:
  apt:
    sources:
#    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - sourceline: 'ppa:beineri/opt-qt-5.12.3-bionic'
    packages:
#    - gcc-9
#    - g++-9
    - qt512base
    - qt512charts-no-lgpl
    - qt512script
    - qt512tools
    - mesa-common-dev
    - libgl1-mesa-dev
    
script:
  - source /opt/qt512/bin/qt512-env.sh
  - /opt/qt512/bin/qmake Loja.pro
  - make -j2
  
before_cache:
  - ccache --show-stats