language: cpp
cache: ccache
sudo: required
dist: trusty
compiler: gcc clang

#matrix:
#  include:
#    - compiler: gcc
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - gcc-7
#            - g++-7
#      env: QT=g++
#      env: CXX=g++-7
#      env: CC=gcc-7
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - clang-3.9
#      env: QT=clang++
    
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
  - sudo apt-get update

install:
  #- sudo apt-get install -y qt59-meta-full dh-make
  
script:
  #- if [[ "${compiler}" == "g++" ]]; then echo "g++"; fi
  - if [[ "${compiler}" == "g++" ]]; then sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc; fi
  - if [[ "${compiler}" == "g++" ]]; then sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++; fi
  #- if [[ "${compiler}" == "clang++" ]]; then echo "clang"; fi
  - if [[ "${compiler}" == "clang++" ]]; then sudo ln -s /usr/bin/clang-3.9 /usr/local/bin/gcc; fi
  - if [[ "${compiler}" == "clang++" ]]; then sudo ln -s /usr/bin/clang++-3.9 /usr/local/bin/g++; fi

  # Link gcc-7 and g++-7 to their standard commands
  #- sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  #- sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v
  # Run your build commands next
  #- source /opt/qt59/bin/qt59-env.sh
  #- /opt/qt59/bin/qmake Loja.pro
  #- ccache make -j4
