language: cpp
compiler: gcc
dist: bionic
cache: ccache

addons:
  apt:
    sources:
    - sourceline: 'ppa:beineri/opt-qt-5.14.2-bionic'
    packages:
    - qt514base
    - qt514charts-no-lgpl
    - qt514tools
    - qt514svg
    - mesa-common-dev
    - libgl1-mesa-dev
    
script:
  - source /opt/qt514/bin/qt514-env.sh
  - /opt/qt514/bin/qmake Loja.pro
  - make -j2
  
before_cache:
  - ccache --show-stats