language: cpp
compiler: gcc
sudo: false
dist: xenial
cache: ccache

addons:
  apt:
    sources:
    - ppa:ubuntu-toolchain-r/test
    - ppa:beineri/opt-qt-5.11.2-xenial
    packages:
    - gcc-7
    - g++-7
    - qt511base
    - qt511charts-no-lgpl
    - qt511script
    - qt511tools
    
script:
  - source /opt/qt511/bin/qt511-env.sh
  - /opt/qt511/bin/qmake Loja.pro
  - make -j4
  
before_cache:
  - ccache --show-stats