language: cpp
cache: ccache
sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env: COMPILER=g++-7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
      env: COMPILER=clang++-3.9
    
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
  #- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update

install:
  #- echo "${compiler}"
  #- echo "$compiler"
  - sudo apt-get install -y qt59-meta-full dh-make
  #- if [[ "${compiler}" == "gcc" ]]; then sudo apt-get install g++-7; fi
  #- if [[ "${compiler}" == "clang" ]]; then sudo apt-get install clang-3.9; fi
  
script:
  #- if [[ "${compiler}" == "gcc" ]]; then echo "g++"; fi
  #- if [[ "${compiler}" == "gcc" ]]; then sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc; fi
  #- if [[ "${compiler}" == "gcc" ]]; then sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++; fi
  #- if [[ "${compiler}" == "clang" ]]; then echo "clang"; fi
  #- if [[ "${compiler}" == "clang" ]]; then sudo ln -s /usr/bin/clang-3.9 /usr/local/bin/gcc; fi
  #- if [[ "${compiler}" == "clang" ]]; then sudo ln -s /usr/bin/clang++-3.9 /usr/local/bin/g++; fi
  
  #- if [[ "${compiler}" == "gcc" ]]; then echo "gcc"; fi
  #- if [[ "${compiler}" == "clang" ]]; then echo "clang"; fi

  # Link gcc-7 and g++-7 to their standard commands
  #- sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  #- sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  # Check versions of gcc, g++ and cmake
  #- gcc -v && g++ -v
  # Run your build commands next
  - source /opt/qt59/bin/qt59-env.sh
  - if [ "$COMPILER" = "g++-7" ]; then /opt/qt59/bin/qmake Loja.pro; fi
  - if [ "$COMPILER" = "clang++-3.9" ]; then /opt/qt59/bin/qmake Loja.pro -spec linux-clang; fi
  - ccache make CXX=$COMPILER -j3
