language: cpp

dist: trusty

env:
  - QT=qt59

apt:
  sources:
  - ubuntu-toolchain-r-test
  packages:
  - gcc-4.8
  - g++-4.8

branches:
  only:
    - 'master'
    
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y && sudo apt-get update;

install:
  - sudo apt-get install -y qt59base qt59script dh-make;

#before_script:
#  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
#      export DISPLAY=:99.0
#      && sh -e /etc/init.d/xvfb start;
#    fi;

script:
  - source /opt/qt59/bin/qt59-env.sh;
  - qmake -r Loja.pro
  - make -j4
  - make all;
