language: cpp
cache: ccache
sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env: COMPILER=g++
#      env: CXX=g++-7
#      env: CC=gcc-7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
      env: COMPILER=clang++
    
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
  - sudo apt-get update

install:
  - sudo apt-get install -y qt59-meta-full dh-make
  
script:
  - if ["$COMPILER" = "g++"]; then
  # Link gcc-7 and g++-7 to their standard commands
      echo "g++"
      sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
      sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++;
    else
  # Link gcc-7 and g++-7 to their standard commands
      echo "clang"
      sudo ln -s /usr/bin/clang-3.9 /usr/local/bin/gcc
      sudo ln -s /usr/bin/clang++-3.9 /usr/local/bin/g++;
    fi;


  # Link gcc-7 and g++-7 to their standard commands
  #- sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  #- sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v
  # Run your build commands next
  #- source /opt/qt59/bin/qt59-env.sh
  #- /opt/qt59/bin/qmake Loja.pro
  #- ccache make -j4
