language: cpp
compiler: gcc
sudo: false
dist: trusty

cache:
  apt: true

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - sourceline: 'ppa:beineri/opt-qt-5.10.1-trusty'
    packages:
    - gcc-7
    - g++-7
    - qt510base
    - qt510charts-no-lgpl
    - qt510script
    - qt510tools
    
script:
  - source /opt/qt510/bin/qt510-env.sh
  - /opt/qt510/bin/qmake Loja.pro
  - make -j4