language: cpp

dist: trusty

env:
  - QT=qt59

apt:
  sources:
  - ubuntu-toolchain-r-test
  - beineri/opt-qt591-trusty
  packages:
  - gcc-6
  - g++-6

branches:
  only:
    - 'master'
    
before_install:
  - sudo apt-get update;

install:
  - sudo apt-get install -y qt59-meta-full
#  - sudo apt-get install -y qt59base qt59script qttools5-dev qttools5-dev-tools qt5-default libqt5designer5 dh-make;
  
script:
  - source /opt/qt59/bin/qt59-env.sh;
  - /opt/qt59/bin/qmake Loja.pro
  - make -j4
